### PR TITLE
Treat time of undefined as 0 when converting ns to midi.

### LINKED ISSUE #302: Groove returns a note sequence that doesn't have tempos set correctly
It seems that if I do:
```
const recon = await grooveModel.decode(z, temp, undefined, 4, someTempo);
const m = mm.sequenceProtoToMidi(recon[0])
```
This throws a `Uncaught Error: NoteSequence must have exactly 1 tempo at time 0"` on the last line. We probably should set the tempos correctly.

### PR DESCRIPTION
**Pull request by adarob**
Fixes #302

### CODE REVIEW

File: music/src/core/midi_io.ts [hunk 1]
```diff
@@ -120,18 +120,21 @@ export function sequenceProtoToMidi(ns: INoteSequence) {
...
+
   if (!ns.tempos || ns.tempos.length === 0) {
     ns.tempos = [{time: 0, qpm: constants.DEFAULT_QUARTERS_PER_MINUTE}];
   }
   if (!ns.timeSignatures || ns.timeSignatures.length === 0) {
     ns.timeSignatures = [{time: 0, numerator: 4, denominator: 4}];
   }
 
-  if (ns.tempos.length !== 1 || ns.tempos[0].time !== 0) {
+  if (ns.tempos.length !== 1 || isZeroOrUndefined(ns.tempos[0].time)) {
```
Comment (notwaldorf) [inline music/src/core/midi_io.ts]: Don’t you want the negation here, since it said !== 0 originally?

File: music/src/core/midi_io.ts [hunk 2]
```diff
@@ -120,18 +120,21 @@ export function sequenceProtoToMidi(ns: INoteSequence) {
...
     throw new MidiConversionError(
         'NoteSequence must have exactly 1 tempo at time 0');
   }
-  if (ns.timeSignatures.length !== 1 || ns.timeSignatures[0].time !== 0) {
+  if (ns.timeSignatures.length !== 1 ||
+      isZeroOrUndefined(ns.timeSignatures[0].time)) {
```
Comment (notwaldorf) [inline music/src/core/midi_io.ts]: Here too
